export type FieldType =
  | 'text'
  | 'textarea'
  | 'number'
  | 'select'
  | 'multi_select'
  | 'toggle'
  | 'url'
  | 'file'
  | 'status'
  | 'duration'
  | 'structure';

export interface CapabilityField {
  id: string;
  label: string;
  type: FieldType;
  required?: boolean;
  defaultValue?: string | number | boolean;
  placeholder?: string;
  helpText?: string;
  options?: Array<{ value: string; label: string }>;
  statusCapabilityId?: string;
  visibleWhen?: Record<string, string | boolean>;
}

export interface CapabilityUiMode {
  id: string;
  label: string;
  shortLabel: string;
  category: string;
  description: string;
  requestCapability: string;
  statusCapabilityId: string;
  knownRoute?: string;
  artifactType?: string;
  adminOnly?: boolean;
  adultPrivate?: boolean;
  appUsable: boolean;
  proofRequirements?: string[];
  fields: CapabilityField[];
  musicSubSections?: string[];
}

export const CAPABILITY_UI_MODES: readonly CapabilityUiMode[] = [
  {
    id: 'chat',
    label: 'Chat',
    shortLabel: 'Chat',
    category: 'text',
    description: 'Conversational AI chat with optional memory and streaming.',
    requestCapability: 'chat',
    statusCapabilityId: 'chat',
    knownRoute: '/chat',
    artifactType: 'chat_message',
    appUsable: true,
    fields: [
      { id: 'prompt', label: 'Prompt', type: 'textarea', required: true, placeholder: 'Enter your message…' },
      {
        id: 'quality',
        label: 'Quality',
        type: 'select',
        options: [
          { value: 'cheap', label: 'Cheap' },
          { value: 'balanced', label: 'Balanced' },
          { value: 'premium', label: 'Premium' },
        ],
        defaultValue: 'balanced',
      },
      { id: 'save_artifact', label: 'Save Artifact', type: 'toggle', defaultValue: false },
      { id: 'memory', label: 'Memory', type: 'toggle', defaultValue: false },
      { id: 'streaming', label: 'Streaming', type: 'toggle', defaultValue: true },
    ],
  },
  {
    id: 'image',
    label: 'Image Generation',
    shortLabel: 'Image',
    category: 'image',
    description: 'Generate images from text prompts.',
    requestCapability: 'image_generation',
    statusCapabilityId: 'image_generation',
    knownRoute: '/image',
    artifactType: 'image',
    appUsable: true,
    fields: [
      { id: 'prompt', label: 'Prompt', type: 'textarea', required: true, placeholder: 'Describe the image…' },
      { id: 'negative_prompt', label: 'Negative Prompt', type: 'textarea', placeholder: 'What to avoid…' },
      {
        id: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'photorealistic', label: 'Photorealistic' },
          { value: 'anime', label: 'Anime' },
          { value: 'illustration', label: 'Illustration' },
          { value: 'oil_painting', label: 'Oil Painting' },
          { value: 'watercolor', label: 'Watercolor' },
          { value: 'sketch', label: 'Sketch' },
        ],
      },
      {
        id: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'select',
        options: [
          { value: '1:1', label: '1:1 Square' },
          { value: '16:9', label: '16:9 Landscape' },
          { value: '9:16', label: '9:16 Portrait' },
          { value: '4:3', label: '4:3' },
          { value: '3:4', label: '3:4' },
        ],
        defaultValue: '1:1',
      },
      { id: 'count', label: 'Count', type: 'number', defaultValue: 1 },
      {
        id: 'quality',
        label: 'Quality',
        type: 'select',
        options: [
          { value: 'cheap', label: 'Cheap' },
          { value: 'balanced', label: 'Balanced' },
          { value: 'premium', label: 'Premium' },
        ],
        defaultValue: 'balanced',
      },
      { id: 'seed', label: 'Seed', type: 'number', placeholder: 'Random' },
    ],
  },
  {
    id: 'video',
    label: 'Video Generation',
    shortLabel: 'Video',
    category: 'video',
    description: 'Generate short videos from text prompts.',
    requestCapability: 'video_generation',
    statusCapabilityId: 'video_generation',
    knownRoute: '/video',
    artifactType: 'video',
    appUsable: true,
    fields: [
      { id: 'prompt', label: 'Prompt', type: 'textarea', required: true, placeholder: 'Describe the video…' },
      { id: 'duration', label: 'Duration', type: 'duration' },
      {
        id: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'select',
        options: [
          { value: '16:9', label: '16:9 Landscape' },
          { value: '9:16', label: '9:16 Portrait' },
          { value: '1:1', label: '1:1 Square' },
        ],
        defaultValue: '16:9',
      },
      {
        id: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'cinematic', label: 'Cinematic' },
          { value: 'animation', label: 'Animation' },
          { value: 'documentary', label: 'Documentary' },
          { value: 'vlog', label: 'Vlog' },
        ],
      },
      { id: 'count', label: 'Count', type: 'number', defaultValue: 1 },
      {
        id: 'quality',
        label: 'Quality',
        type: 'select',
        options: [
          { value: 'cheap', label: 'Cheap' },
          { value: 'balanced', label: 'Balanced' },
          { value: 'premium', label: 'Premium' },
        ],
        defaultValue: 'balanced',
      },
    ],
  },
  {
    id: 'long_form_video',
    label: 'Long-Form Video',
    shortLabel: 'Long Video',
    category: 'video',
    description: 'Generate multi-scene long-form videos.',
    requestCapability: 'long_form_video_generation',
    statusCapabilityId: 'long_form_video_generation',
    knownRoute: '/long-video',
    artifactType: 'video',
    appUsable: false,
    fields: [
      { id: 'prompt', label: 'Prompt', type: 'textarea', required: true, placeholder: 'Describe the full video…' },
      { id: 'target_duration', label: 'Target Duration', type: 'duration' },
      { id: 'scene_count', label: 'Scene Count', type: 'number', defaultValue: 5 },
      { id: 'scene_length', label: 'Scene Length', type: 'duration' },
      {
        id: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'cinematic', label: 'Cinematic' },
          { value: 'documentary', label: 'Documentary' },
          { value: 'explainer', label: 'Explainer' },
          { value: 'vlog', label: 'Vlog' },
        ],
      },
      {
        id: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'select',
        options: [
          { value: '16:9', label: '16:9 Landscape' },
          { value: '9:16', label: '9:16 Portrait' },
          { value: '1:1', label: '1:1 Square' },
        ],
        defaultValue: '16:9',
      },
      { id: 'voice', label: 'Voiceover', type: 'toggle', defaultValue: false },
      { id: 'music', label: 'Background Music', type: 'toggle', defaultValue: false },
      { id: 'stitching', label: 'Auto-Stitch Scenes', type: 'toggle', defaultValue: true },
      { id: 'production_notes', label: 'Production Notes', type: 'textarea', placeholder: 'Additional instructions…' },
    ],
  },
  {
    id: 'image_to_video',
    label: 'Image to Video',
    shortLabel: 'Img→Video',
    category: 'video',
    description: 'Animate a reference image into a video.',
    requestCapability: 'image_to_video_generation',
    statusCapabilityId: 'image_to_video_generation',
    knownRoute: '/image-to-video',
    artifactType: 'video',
    appUsable: false,
    fields: [
      { id: 'prompt', label: 'Motion Prompt', type: 'textarea', required: true, placeholder: 'Describe the motion…' },
      { id: 'reference_image', label: 'Reference Image URL', type: 'url', required: true },
      { id: 'duration', label: 'Duration', type: 'duration' },
      {
        id: 'aspect_ratio',
        label: 'Aspect Ratio',
        type: 'select',
        options: [
          { value: '16:9', label: '16:9 Landscape' },
          { value: '9:16', label: '9:16 Portrait' },
          { value: '1:1', label: '1:1 Square' },
        ],
        defaultValue: '16:9',
      },
      {
        id: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'cinematic', label: 'Cinematic' },
          { value: 'animation', label: 'Animation' },
          { value: 'realistic', label: 'Realistic' },
        ],
      },
    ],
  },
  {
    id: 'music',
    label: 'Music Generation',
    shortLabel: 'Music',
    category: 'audio',
    description: 'Generate original music tracks with full production controls.',
    requestCapability: 'music_generation',
    statusCapabilityId: 'music_generation',
    knownRoute: '/music',
    artifactType: 'audio',
    appUsable: true,
    musicSubSections: ['Song', 'Lyrics', 'Production', 'Structure', 'Remix / Variations', 'Video / Outputs'],
    fields: [
      // Song
      {
        id: 'theme',
        label: 'Theme / Prompt',
        type: 'textarea',
        placeholder: 'Describe the mood, theme, or concept of the song…',
      },
      // Lyrics
      { id: 'lyrics', label: 'Lyrics', type: 'textarea', placeholder: 'Enter custom lyrics or leave blank to auto-generate…' },
      { id: 'generate_lyrics', label: 'Auto-Generate Lyrics', type: 'toggle', defaultValue: false },
      // Production
      {
        id: 'genre',
        label: 'Genre',
        type: 'select',
        options: [
          { value: 'pop', label: 'Pop' },
          { value: 'rock', label: 'Rock' },
          { value: 'jazz', label: 'Jazz' },
          { value: 'hip-hop', label: 'Hip-Hop' },
          { value: 'electronic', label: 'Electronic' },
          { value: 'classical', label: 'Classical' },
          { value: 'country', label: 'Country' },
          { value: 'r&b', label: 'R&B' },
          { value: 'folk', label: 'Folk' },
          { value: 'metal', label: 'Metal' },
        ],
      },
      {
        id: 'genres_multi',
        label: 'Genres (Multi)',
        type: 'multi_select',
        options: [
          { value: 'pop', label: 'Pop' },
          { value: 'rock', label: 'Rock' },
          { value: 'jazz', label: 'Jazz' },
          { value: 'hip-hop', label: 'Hip-Hop' },
          { value: 'electronic', label: 'Electronic' },
          { value: 'classical', label: 'Classical' },
          { value: 'country', label: 'Country' },
          { value: 'r&b', label: 'R&B' },
          { value: 'folk', label: 'Folk' },
          { value: 'metal', label: 'Metal' },
        ],
      },
      { id: 'bpm', label: 'BPM', type: 'number', defaultValue: 120 },
      {
        id: 'key',
        label: 'Key',
        type: 'select',
        options: [
          { value: 'C', label: 'C Major' },
          { value: 'Cm', label: 'C Minor' },
          { value: 'D', label: 'D Major' },
          { value: 'Dm', label: 'D Minor' },
          { value: 'E', label: 'E Major' },
          { value: 'Em', label: 'E Minor' },
          { value: 'F', label: 'F Major' },
          { value: 'Fm', label: 'F Minor' },
          { value: 'G', label: 'G Major' },
          { value: 'Gm', label: 'G Minor' },
          { value: 'A', label: 'A Major' },
          { value: 'Am', label: 'A Minor' },
          { value: 'B', label: 'B Major' },
          { value: 'Bm', label: 'B Minor' },
        ],
      },
      {
        id: 'mood',
        label: 'Mood',
        type: 'select',
        options: [
          { value: 'happy', label: 'Happy' },
          { value: 'sad', label: 'Sad' },
          { value: 'energetic', label: 'Energetic' },
          { value: 'calm', label: 'Calm' },
          { value: 'romantic', label: 'Romantic' },
          { value: 'dark', label: 'Dark' },
          { value: 'epic', label: 'Epic' },
          { value: 'playful', label: 'Playful' },
        ],
      },
      {
        id: 'vocal_mode',
        label: 'Vocal Mode',
        type: 'select',
        options: [
          { value: 'vocal', label: 'Vocal' },
          { value: 'instrumental', label: 'Instrumental' },
          { value: 'no_vocal', label: 'No Vocal' },
        ],
        defaultValue: 'vocal',
      },
      {
        id: 'vocal_style',
        label: 'Vocal Style',
        type: 'select',
        options: [
          { value: 'pop', label: 'Pop' },
          { value: 'opera', label: 'Opera' },
          { value: 'rap', label: 'Rap' },
          { value: 'soulful', label: 'Soulful' },
          { value: 'breathy', label: 'Breathy' },
          { value: 'powerful', label: 'Powerful' },
        ],
      },
      // Structure
      { id: 'target_duration', label: 'Target Duration', type: 'duration' },
      { id: 'track_count', label: 'Track Count', type: 'number', defaultValue: 1 },
      { id: 'instrumental_only', label: 'Instrumental Only', type: 'toggle', defaultValue: false },
      {
        id: 'quality',
        label: 'Quality',
        type: 'select',
        options: [
          { value: 'cheap', label: 'Cheap' },
          { value: 'balanced', label: 'Balanced' },
          { value: 'premium', label: 'Premium' },
        ],
        defaultValue: 'balanced',
      },
      // Remix / Variations
      { id: 'remix', label: 'Remix', type: 'toggle', defaultValue: false },
      {
        id: 'remix_style',
        label: 'Remix Style',
        type: 'select',
        visibleWhen: { remix: true },
        options: [
          { value: 'acoustic', label: 'Acoustic' },
          { value: 'edm', label: 'EDM' },
          { value: 'lofi', label: 'Lo-Fi' },
          { value: 'orchestral', label: 'Orchestral' },
          { value: 'jazz', label: 'Jazz' },
        ],
      },
      // Outputs
      { id: 'stems', label: 'Stems', type: 'status', statusCapabilityId: 'music_generation' },
      { id: 'cover_art', label: 'Cover Art', type: 'status', statusCapabilityId: 'image_generation' },
      { id: 'music_video', label: 'Music Video', type: 'toggle', defaultValue: false },
      {
        id: 'music_video_style',
        label: 'Music Video Style',
        type: 'select',
        visibleWhen: { music_video: true },
        options: [
          { value: 'lyric', label: 'Lyric Video' },
          { value: 'cinematic', label: 'Cinematic' },
          { value: 'visualizer', label: 'Visualizer' },
          { value: 'animated', label: 'Animated' },
        ],
      },
      { id: 'lyric_video', label: 'Lyric Video', type: 'toggle', defaultValue: false },
      { id: 'download_artifact', label: 'Download', type: 'status', statusCapabilityId: 'music_generation' },
    ],
  },
  {
    id: 'tts',
    label: 'Text to Speech',
    shortLabel: 'TTS',
    category: 'audio',
    description: 'Convert text to natural-sounding speech.',
    requestCapability: 'tts',
    statusCapabilityId: 'tts',
    knownRoute: '/tts',
    artifactType: 'audio',
    appUsable: true,
    fields: [
      { id: 'text', label: 'Text', type: 'textarea', required: true, placeholder: 'Enter text to convert to speech…' },
      {
        id: 'voice',
        label: 'Voice',
        type: 'select',
        options: [
          { value: 'alloy', label: 'Alloy' },
          { value: 'echo', label: 'Echo' },
          { value: 'fable', label: 'Fable' },
          { value: 'onyx', label: 'Onyx' },
          { value: 'nova', label: 'Nova' },
          { value: 'shimmer', label: 'Shimmer' },
        ],
        defaultValue: 'alloy',
      },
      {
        id: 'language',
        label: 'Language',
        type: 'select',
        options: [
          { value: 'en', label: 'English' },
          { value: 'es', label: 'Spanish' },
          { value: 'fr', label: 'French' },
          { value: 'de', label: 'German' },
          { value: 'it', label: 'Italian' },
          { value: 'pt', label: 'Portuguese' },
          { value: 'zh', label: 'Chinese' },
          { value: 'ja', label: 'Japanese' },
          { value: 'ko', label: 'Korean' },
          { value: 'ar', label: 'Arabic' },
        ],
        defaultValue: 'en',
      },
      { id: 'speed', label: 'Speed', type: 'number', defaultValue: 1.0 },
      {
        id: 'emotion',
        label: 'Emotion',
        type: 'select',
        options: [
          { value: 'neutral', label: 'Neutral' },
          { value: 'happy', label: 'Happy' },
          { value: 'sad', label: 'Sad' },
          { value: 'excited', label: 'Excited' },
          { value: 'calm', label: 'Calm' },
        ],
        defaultValue: 'neutral',
      },
      {
        id: 'output_format',
        label: 'Output Format',
        type: 'select',
        options: [
          { value: 'mp3', label: 'MP3' },
          { value: 'wav', label: 'WAV' },
          { value: 'flac', label: 'FLAC' },
          { value: 'ogg', label: 'OGG' },
        ],
        defaultValue: 'mp3',
      },
    ],
  },
  {
    id: 'stt',
    label: 'Speech to Text',
    shortLabel: 'STT',
    category: 'audio',
    description: 'Transcribe audio or video files to text.',
    requestCapability: 'stt',
    statusCapabilityId: 'stt',
    knownRoute: '/stt',
    artifactType: 'text',
    appUsable: true,
    fields: [
      { id: 'audio', label: 'Audio File', type: 'file', required: true },
      {
        id: 'language',
        label: 'Language',
        type: 'select',
        options: [
          { value: 'auto', label: 'Auto-detect' },
          { value: 'en', label: 'English' },
          { value: 'es', label: 'Spanish' },
          { value: 'fr', label: 'French' },
          { value: 'de', label: 'German' },
          { value: 'zh', label: 'Chinese' },
          { value: 'ja', label: 'Japanese' },
          { value: 'ko', label: 'Korean' },
          { value: 'ar', label: 'Arabic' },
        ],
        defaultValue: 'auto',
      },
      { id: 'diarization', label: 'Speaker Diarization', type: 'toggle', defaultValue: false },
      { id: 'timestamps', label: 'Include Timestamps', type: 'toggle', defaultValue: false },
      { id: 'translate', label: 'Translate to English', type: 'toggle', defaultValue: false },
    ],
  },
  {
    id: 'avatar',
    label: 'Avatar',
    shortLabel: 'Avatar',
    category: 'video',
    description: 'Create a talking avatar from an image with voice and script.',
    requestCapability: 'avatar_generation',
    statusCapabilityId: 'avatar_generation',
    knownRoute: '/avatar',
    artifactType: 'video',
    appUsable: false,
    fields: [
      { id: 'avatar_name', label: 'Avatar Name', type: 'text', placeholder: 'Name your avatar…' },
      {
        id: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'realistic', label: 'Realistic' },
          { value: 'animated', label: 'Animated' },
          { value: 'cartoon', label: 'Cartoon' },
          { value: 'sketch', label: 'Sketch' },
        ],
      },
      { id: 'reference_image', label: 'Reference Image URL', type: 'url' },
      {
        id: 'mode',
        label: 'Mode',
        type: 'select',
        options: [
          { value: 'image', label: 'Image' },
          { value: 'video', label: 'Video' },
        ],
        defaultValue: 'video',
      },
      {
        id: 'voice',
        label: 'Voice',
        type: 'select',
        options: [
          { value: 'alloy', label: 'Alloy' },
          { value: 'echo', label: 'Echo' },
          { value: 'nova', label: 'Nova' },
          { value: 'shimmer', label: 'Shimmer' },
        ],
      },
      { id: 'script', label: 'Script', type: 'textarea', placeholder: 'What should the avatar say?' },
      { id: 'lip_sync', label: 'Lip Sync', type: 'status', statusCapabilityId: 'avatar_generation' },
    ],
  },
  {
    id: 'research_rag',
    label: 'Research / RAG',
    shortLabel: 'Research',
    category: 'text',
    description: 'Deep research with retrieval-augmented generation and source citations.',
    requestCapability: 'research_rag',
    statusCapabilityId: 'research_rag',
    knownRoute: '/research',
    artifactType: 'document',
    appUsable: true,
    fields: [
      { id: 'question', label: 'Research Question', type: 'textarea', required: true, placeholder: 'What do you want to research?' },
      { id: 'url', label: 'Source URL', type: 'url', placeholder: 'Optional URL to include as source…' },
      {
        id: 'depth',
        label: 'Research Depth',
        type: 'select',
        options: [
          { value: 'quick', label: 'Quick' },
          { value: 'standard', label: 'Standard' },
          { value: 'deep', label: 'Deep' },
        ],
        defaultValue: 'standard',
      },
      { id: 'cite_sources', label: 'Cite Sources', type: 'toggle', defaultValue: true },
      { id: 'memory_ingest', label: 'Ingest into Memory', type: 'toggle', defaultValue: false },
    ],
  },
  {
    id: 'campaign',
    label: 'Campaign',
    shortLabel: 'Campaign',
    category: 'marketing',
    description: 'Generate multi-channel marketing campaigns.',
    requestCapability: 'campaign_generation',
    statusCapabilityId: 'campaign_generation',
    knownRoute: '/campaign',
    artifactType: 'campaign',
    appUsable: true,
    fields: [
      { id: 'brand', label: 'Brand', type: 'text', required: true, placeholder: 'Brand name…' },
      { id: 'objective', label: 'Campaign Objective', type: 'textarea', required: true, placeholder: 'What is the goal of this campaign?' },
      { id: 'audience', label: 'Target Audience', type: 'text', placeholder: 'Describe your target audience…' },
      {
        id: 'channels',
        label: 'Channels',
        type: 'multi_select',
        options: [
          { value: 'instagram', label: 'Instagram' },
          { value: 'twitter', label: 'Twitter / X' },
          { value: 'facebook', label: 'Facebook' },
          { value: 'linkedin', label: 'LinkedIn' },
          { value: 'tiktok', label: 'TikTok' },
          { value: 'youtube', label: 'YouTube' },
          { value: 'email', label: 'Email' },
        ],
      },
      { id: 'posts_count', label: 'Number of Posts', type: 'number', defaultValue: 5 },
      {
        id: 'tone',
        label: 'Tone',
        type: 'select',
        options: [
          { value: 'professional', label: 'Professional' },
          { value: 'casual', label: 'Casual' },
          { value: 'humorous', label: 'Humorous' },
          { value: 'inspirational', label: 'Inspirational' },
          { value: 'urgent', label: 'Urgent' },
        ],
        defaultValue: 'professional',
      },
      {
        id: 'approval_mode',
        label: 'Approval Mode',
        type: 'select',
        options: [
          { value: 'auto', label: 'Auto-publish' },
          { value: 'manual', label: 'Manual Review' },
          { value: 'draft', label: 'Draft Only' },
        ],
        defaultValue: 'draft',
      },
    ],
  },
  {
    id: 'automation',
    label: 'Automation',
    shortLabel: 'Automation',
    category: 'ops',
    description: 'Create automated workflows triggered by events or schedules.',
    requestCapability: 'automation',
    statusCapabilityId: 'automation',
    knownRoute: '/automation',
    artifactType: 'automation',
    adminOnly: true,
    appUsable: false,
    fields: [
      { id: 'name', label: 'Automation Name', type: 'text', required: true, placeholder: 'Name this automation…' },
      {
        id: 'capability',
        label: 'Capability',
        type: 'select',
        options: [
          { value: 'chat', label: 'Chat' },
          { value: 'image_generation', label: 'Image Generation' },
          { value: 'music_generation', label: 'Music Generation' },
          { value: 'campaign_generation', label: 'Campaign' },
          { value: 'publishing', label: 'Publishing' },
        ],
      },
      {
        id: 'trigger',
        label: 'Trigger',
        type: 'select',
        options: [
          { value: 'schedule', label: 'Schedule' },
          { value: 'webhook', label: 'Webhook' },
          { value: 'event', label: 'Event' },
          { value: 'manual', label: 'Manual' },
        ],
        defaultValue: 'manual',
      },
      { id: 'schedule', label: 'Schedule (CRON)', type: 'text', placeholder: '0 9 * * 1 (every Monday 9am)' },
      { id: 'approval_required', label: 'Approval Required', type: 'toggle', defaultValue: true },
    ],
  },
  {
    id: 'publishing',
    label: 'Publishing',
    shortLabel: 'Publish',
    category: 'marketing',
    description: 'Schedule and publish content to social platforms.',
    requestCapability: 'publishing',
    statusCapabilityId: 'publishing',
    knownRoute: '/publishing',
    artifactType: 'post',
    adminOnly: true,
    appUsable: false,
    fields: [
      {
        id: 'platform',
        label: 'Platform',
        type: 'multi_select',
        required: true,
        options: [
          { value: 'instagram', label: 'Instagram' },
          { value: 'twitter', label: 'Twitter / X' },
          { value: 'facebook', label: 'Facebook' },
          { value: 'linkedin', label: 'LinkedIn' },
          { value: 'tiktok', label: 'TikTok' },
          { value: 'youtube', label: 'YouTube' },
        ],
      },
      { id: 'content', label: 'Content', type: 'textarea', required: true, placeholder: 'Post content…' },
      { id: 'schedule_time', label: 'Schedule Time', type: 'text', placeholder: 'ISO datetime or "now"' },
      { id: 'approval_required', label: 'Approval Required', type: 'toggle', defaultValue: true },
    ],
  },
  {
    id: 'trading',
    label: 'Trading',
    shortLabel: 'Trading',
    category: 'finance',
    description: 'Automated trading strategy execution.',
    requestCapability: 'trading',
    statusCapabilityId: 'trading',
    knownRoute: '/trading',
    artifactType: 'trade',
    adminOnly: true,
    appUsable: false,
    fields: [
      { id: 'strategy', label: 'Strategy', type: 'textarea', required: true, placeholder: 'Describe trading strategy…' },
      { id: 'symbol', label: 'Symbol', type: 'text', required: true, placeholder: 'e.g. BTC/USD, AAPL' },
      {
        id: 'timeframe',
        label: 'Timeframe',
        type: 'select',
        options: [
          { value: '1m', label: '1 Minute' },
          { value: '5m', label: '5 Minutes' },
          { value: '15m', label: '15 Minutes' },
          { value: '1h', label: '1 Hour' },
          { value: '4h', label: '4 Hours' },
          { value: '1d', label: '1 Day' },
        ],
        defaultValue: '1h',
      },
      { id: 'max_position', label: 'Max Position Size', type: 'number' },
      { id: 'daily_loss_limit', label: 'Daily Loss Limit', type: 'number' },
    ],
  },
  {
    id: 'adult_private',
    label: 'Adult (Private)',
    shortLabel: 'Adult',
    category: 'adult',
    description: 'Adult content generation — age-verified and private.',
    requestCapability: 'adult_private',
    statusCapabilityId: 'adult_private',
    knownRoute: '/adult',
    artifactType: 'adult',
    adminOnly: true,
    adultPrivate: true,
    appUsable: false,
    proofRequirements: ['age_verification', 'consent'],
    fields: [
      { id: 'adult_text', label: 'Text Generation', type: 'status', statusCapabilityId: 'adult_private' },
      { id: 'adult_image', label: 'Image Generation', type: 'status', statusCapabilityId: 'adult_private' },
      { id: 'adult_voice', label: 'Voice Generation', type: 'status', statusCapabilityId: 'adult_private' },
      { id: 'adult_avatar', label: 'Avatar Generation', type: 'status', statusCapabilityId: 'adult_private' },
      { id: 'adult_video', label: 'Video Generation', type: 'status', statusCapabilityId: 'adult_private' },
    ],
  },
] as const;
