'use client'

import { useCallback, useEffect, useState } from 'react'
import { RefreshCw } from 'lucide-react'
import { listAssets, type AssetSummary } from '@/lib/dashboard-api'
import { EmptyState, ErrorState, LoadingState, PageHeader, SectionCard, StatusBadge } from '@/components/dashboard/ui'

export default function AssetsPage() {
  const [assets, setAssets] = useState<AssetSummary[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const load = useCallback(async () => {
    setError(null)
    const result = await listAssets()
    if (result.ok && result.data) {
      setAssets(result.data)
    } else {
      setError(result.error ?? 'Failed to load assets')
    }
    setLoading(false)
  }, [])

  useEffect(() => { void load() }, [load])

  return (
    <div className="space-y-5">
      <PageHeader
        label="Assets"
        title="Generated Assets"
        description="All media and content assets generated by AmarktAI workflows."
        badge={
          <button onClick={load} className="flex items-center gap-1.5 rounded-xl border border-slate-700 bg-slate-800/60 px-3 py-2 text-xs font-bold text-slate-300 hover:bg-slate-800">
            <RefreshCw className="h-3.5 w-3.5" /> Refresh
          </button>
        }
      />

      {loading && <LoadingState label="Loading assets…" />}
      {!loading && error && <ErrorState message={error} retry={load} />}

      {!loading && !error && (
        <SectionCard title={`Assets (${assets.length})`}>
          {assets.length === 0 ? (
            <EmptyState title="No assets yet" description="Assets appear here after a marketing workflow generates them." />
          ) : (
            <div className="space-y-2">
              {assets.map(a => (
                <div key={a.id} className="rounded-xl border border-slate-700/40 bg-slate-950/45 p-4">
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="rounded-md border border-slate-600 bg-slate-800 px-1.5 py-0.5 text-[10px] font-bold text-slate-400">{a.assetType}</span>
                        <span className="text-[10px] text-slate-600">{a.capability}</span>
                      </div>
                      {a.promptSummary && <p className="mt-1 text-xs text-slate-400 line-clamp-2">{a.promptSummary}</p>}
                      <p className="mt-1 text-[10px] text-slate-600">{new Date(a.createdAt).toLocaleDateString()}</p>
                    </div>
                    <div className="flex flex-col items-end gap-1">
                      <StatusBadge status={a.approvalStatus} />
                      <StatusBadge status={a.status} />
                    </div>
                  </div>
                  {a.resultUrl && (
                    <a href={a.resultUrl} target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-xs font-bold text-cyan-400 hover:text-cyan-300">
                      View asset →
                    </a>
                  )}
                  {a.approvalNotes && <p className="mt-1 text-xs text-amber-300 italic">{a.approvalNotes}</p>}
                </div>
              ))}
            </div>
          )}
        </SectionCard>
      )}
    </div>
  )
}
