'use client'

import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import { Megaphone, RefreshCw } from 'lucide-react'
import { listCampaigns, type CampaignSummary } from '@/lib/dashboard-api'
import { EmptyState, ErrorState, LoadingState, PageHeader, SectionCard, StatusBadge } from '@/components/dashboard/ui'

export default function CampaignsPage() {
  const [campaigns, setCampaigns] = useState<CampaignSummary[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const load = useCallback(async () => {
    setError(null)
    const result = await listCampaigns()
    if (result.ok && result.data) {
      setCampaigns(result.data)
    } else {
      setError(result.error ?? 'Failed to load campaigns')
    }
    setLoading(false)
  }, [])

  useEffect(() => { void load() }, [load])

  return (
    <div className="space-y-5">
      <PageHeader
        label="Campaigns"
        title="All Campaigns"
        description="View and manage marketing campaigns generated by AmarktAI."
        badge={
          <button onClick={load} className="flex items-center gap-1.5 rounded-xl border border-slate-700 bg-slate-800/60 px-3 py-2 text-xs font-bold text-slate-300 hover:bg-slate-800">
            <RefreshCw className="h-3.5 w-3.5" /> Refresh
          </button>
        }
      />

      {loading && <LoadingState label="Loading campaigns…" />}
      {!loading && error && <ErrorState message={error} retry={load} />}

      {!loading && !error && (
        <SectionCard title={`Campaigns (${campaigns.length})`}>
          {campaigns.length === 0 ? (
            <EmptyState
              icon={<Megaphone className="h-10 w-10" />}
              title="No campaigns yet"
              description="Run the Marketing Workflow to create your first campaign."
              action={
                <Link href="/admin/dashboard/marketing" className="rounded-xl border border-cyan-500/30 bg-cyan-500/10 px-4 py-2 text-xs font-black text-cyan-300 hover:bg-cyan-500/20">
                  Go to Marketing
                </Link>
              }
            />
          ) : (
            <div className="space-y-2">
              {campaigns.map(c => (
                <Link
                  key={c.id}
                  href={`/admin/dashboard/campaigns/${c.id}`}
                  className="flex flex-wrap items-start justify-between gap-3 rounded-xl border border-slate-700/40 bg-slate-950/45 p-4 transition hover:border-cyan-500/20 hover:bg-slate-900/60"
                >
                  <div>
                    <p className="font-black text-slate-200">{c.name}</p>
                    <p className="mt-0.5 text-xs text-slate-400">{c.goal}</p>
                    <p className="mt-1 text-[10px] text-slate-600">
                      {c.platforms.join(', ')} · {new Date(c.createdAt).toLocaleDateString()}
                    </p>
                  </div>
                  <div className="flex flex-col items-end gap-1">
                    <StatusBadge status={c.status} />
                    <span className="text-[10px] text-slate-500">{c.approvalMode === 'manual_review' ? 'manual review' : 'auto'}</span>
                  </div>
                </Link>
              ))}
            </div>
          )}
        </SectionCard>
      )}
    </div>
  )
}
