import type { ProviderTruthDefinition } from './provider-types'

const CACHE_TTL_MS = 5 * 60 * 1000

export const PROVIDER_TRUTH: readonly ProviderTruthDefinition[] = [
  {
    id: 'huggingface',
    displayName: 'Hugging Face',
    envAliases: ['HUGGINGFACE_API_KEY', 'HUGGINGFACEHUB_API_TOKEN', 'HF_TOKEN'],
    auth: { header: 'Authorization', prefix: 'Bearer ' },
    endpoints: [
      { family: 'hub', baseUrl: 'https://huggingface.co' },
      {
        family: 'inference_router',
        baseUrl: 'https://router.huggingface.co',
        baseUrlEnv: 'HUGGINGFACE_BASE_URL',
      },
    ],
    discovery: {
      models: 'https://huggingface.co/api/models',
      tasks: 'model_metadata',
      providers: 'inferenceProviderMapping',
      privateEndpointsEnv: 'HF_PRIVATE_ENDPOINTS_JSON',
      dedicatedEndpointsEnv: 'HF_DEDICATED_ENDPOINTS_JSON',
      cacheTtlMs: CACHE_TTL_MS,
    },
    capabilities: [
      'chat', 'reasoning', 'coding', 'vision', 'ocr', 'image', 'video', 'music',
      'tts', 'stt', 'embeddings', 'rerank', 'documents', 'translation', 'avatar',
    ],
    features: {
      streaming: true,
      asyncJobs: false,
      webhooks: false,
      toolCalling: false,
      artifactSupport: true,
    },
    billing: { plan: 'account', freeQuotaEligible: 'unknown', pricingSource: 'provider_catalog', staticPrices: false },
  },
  {
    id: 'together',
    displayName: 'Together AI',
    envAliases: ['TOGETHER_API_KEY'],
    auth: { header: 'Authorization', prefix: 'Bearer ' },
    endpoints: [{
      family: 'openai_compatible',
      baseUrl: 'https://api.together.ai/v1',
      baseUrlEnv: 'TOGETHER_BASE_URL',
    }],
    discovery: {
      models: '/models',
      tasks: 'model_metadata',
      providers: null,
      privateEndpointsEnv: null,
      dedicatedEndpointsEnv: 'TOGETHER_DEDICATED_ENDPOINTS_JSON',
      cacheTtlMs: CACHE_TTL_MS,
    },
    capabilities: ['chat', 'reasoning', 'coding', 'image', 'video', 'image_to_video', 'tts', 'stt', 'vision', 'embeddings', 'rerank', 'agents'],
    features: {
      streaming: true,
      asyncJobs: true,
      webhooks: false,
      toolCalling: true,
      artifactSupport: true,
    },
    billing: { plan: 'account', freeQuotaEligible: 'unknown', pricingSource: 'provider_catalog', staticPrices: false },
  },
  {
    id: 'groq',
    displayName: 'Groq',
    envAliases: ['GROQ_API_KEY'],
    auth: { header: 'Authorization', prefix: 'Bearer ' },
    endpoints: [{
      family: 'openai_compatible',
      baseUrl: 'https://api.groq.com/openai/v1',
      baseUrlEnv: 'GROQ_BASE_URL',
    }],
    discovery: {
      models: '/models',
      tasks: 'model_metadata',
      providers: null,
      privateEndpointsEnv: null,
      dedicatedEndpointsEnv: null,
      cacheTtlMs: CACHE_TTL_MS,
    },
    capabilities: ['chat', 'reasoning', 'coding', 'vision', 'tts', 'stt'],
    features: {
      streaming: true,
      asyncJobs: false,
      webhooks: false,
      toolCalling: false,
      artifactSupport: true,
    },
    billing: { plan: 'account', freeQuotaEligible: 'unknown', pricingSource: 'provider_catalog', staticPrices: false },
  },
  {
    id: 'genx',
    displayName: 'GenX',
    envAliases: ['GENX_API_KEY'],
    auth: { header: 'Authorization', prefix: 'Bearer ' },
    endpoints: [
      { family: 'async_generation', baseUrl: 'https://query.genx.sh/api/v1', baseUrlEnv: 'GENX_BASE_URL' },
      { family: 'streaming_text', baseUrl: 'https://query.genx.sh/v1', baseUrlEnv: 'GENX_TEXT_BASE_URL' },
    ],
    discovery: {
      models: '/models',
      tasks: 'model_metadata',
      providers: null,
      privateEndpointsEnv: null,
      dedicatedEndpointsEnv: null,
      cacheTtlMs: CACHE_TTL_MS,
    },
    capabilities: ['chat', 'reasoning', 'coding', 'image', 'video', 'music', 'tts'],
    features: {
      streaming: true,
      asyncJobs: true,
      webhooks: false,
      toolCalling: false,
      artifactSupport: true,
    },
    billing: { plan: 'credits', freeQuotaEligible: false, pricingSource: 'provider_catalog', staticPrices: false },
  },
  {
    id: 'qwen',
    displayName: 'Qwen / DashScope',
    envAliases: ['QWEN_API_KEY', 'DASHSCOPE_API_KEY'],
    auth: { header: 'Authorization', prefix: 'Bearer ' },
    endpoints: [
      {
        family: 'compatible_mode',
        baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
        baseUrlEnv: 'DASHSCOPE_BASE_URL',
      },
      {
        family: 'aigc',
        baseUrl: 'https://dashscope-intl.aliyuncs.com/api/v1',
        baseUrlEnv: 'DASHSCOPE_AIGC_BASE_URL',
      },
    ],
    discovery: {
      models: '/models',
      tasks: 'model_metadata',
      providers: null,
      privateEndpointsEnv: null,
      dedicatedEndpointsEnv: null,
      cacheTtlMs: CACHE_TTL_MS,
    },
    capabilities: ['chat', 'reasoning', 'coding', 'vision', 'ocr', 'image', 'video', 'image_to_video', 'embeddings', 'translation'],
    features: {
      streaming: true,
      asyncJobs: true,
      webhooks: false,
      toolCalling: true,
      artifactSupport: true,
    },
    billing: {
      plan: 'standard_free_quota',
      freeQuotaEligible: true,
      paidEnabledEnv: 'QWEN_PAID_ENABLED',
      pricingSource: 'provider_catalog',
      staticPrices: false,
    },
  },
  {
    id: 'mimo',
    displayName: 'Xiaomi MiMo',
    envAliases: ['MIMO_API_KEY', 'XIAOMI_API_KEY'],
    auth: { header: 'Authorization', prefix: 'Bearer ' },
    endpoints: [{
      family: 'token_plan',
      baseUrl: 'https://token-plan-sgp.xiaomimimo.com/v1',
      baseUrlEnv: 'MIMO_BASE_URL',
    }],
    discovery: {
      models: '/models',
      tasks: 'model_metadata',
      providers: null,
      privateEndpointsEnv: null,
      dedicatedEndpointsEnv: null,
      cacheTtlMs: CACHE_TTL_MS,
    },
    capabilities: ['chat', 'reasoning', 'coding', 'tts'],
    features: {
      streaming: true,
      asyncJobs: false,
      webhooks: false,
      toolCalling: false,
      artifactSupport: false,
    },
    billing: { plan: 'token_plan', freeQuotaEligible: false, pricingSource: 'provider_catalog', staticPrices: false },
  },
] as const
